apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      name: "goserver"
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "fabiosouzadev/k8s-fullcycle:v11"

          startupProbe:
            httpGet:
              path: /healthcheck
              port: 5000
            periodSeconds: 3
            failureThreshold: 10
            initialDelaySeconds: 10
          
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 5000
            periodSeconds: 3
            failureThreshold: 1
            timeoutSeconds: 1

          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 5000
            periodSeconds: 5
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1

          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret
          volumeMounts:
            - mountPath: "/go/myfamily"
              name: config

      volumes:
        - name: config
          configMap:
            name: goserver-family-env
            items:
              - key: members
                path: "family.txt"

# template: define como os pods serão criados.
# Olhe pod.yaml 
### Variaveis de ambiente ###
### USANDO env #####
# ....
# env:
#   - name: NOME
#     value: "Fabio"
#   - name: IDADE
#     value: "36"
# ....
# EXEC
# $ kubectl apply -f k8s/configmap.yaml
# $ kubectl delete deployments.app goserver
# $ kubectl apply -f k8s/deployment.yaml

## Variaveis de ambiente com ConfigMap ##
# ....
# env:
#   - name: NOME
#     valueFrom:
#       configMapKeyRef:
#         name: goserver-env
#         key: NOME
#   - name: IDADE
#     valueFrom:
#       configMapKeyRef:
#         name: goserver-env
#         key: IDADE
# ....
# EXEC
# $ kubectl apply -f k8s/configmap.yaml
# $ kubectl delete deployments.app goserver
# $ kubectl apply -f k8s/deployment.yaml

#### USANDO envFrom (pegando todas as variaveis do ConfigMap) ####
# ....
# spec
#   containers:
# ...
#     envFrom:
#       - configMapRef:
#           name: goserver-env
# ....
# EXEC
# $ kubectl apply -f k8s/configmap.yaml
# $ kubectl delete deployments.app goserver
# $ kubectl apply -f k8s/deployment.yaml

#### Injetando ConfigMap ####
#....
# spec
#   containers:
# ....
#     volumeMounts:
#       - mountPath: "/go/myfamily"
#         name: config
# ....
#   volumes:
#     - name: config
#       configMap:
#         name: goserver-family-env
#         items:
#           - key: members
#             path: "family.txt"
# ....
# EXEC
# $ kubectl apply -f k8s/configmap-family.yaml
# $ kubectl delete deployments.app goserver
# $ kubectl apply -f k8s/deployment.yaml

#### Secret ####
# ....
# spec
#   containers:
# ...
#     envFrom:
#       - secretRef:
#           name: goserver-secret
# ....
# EXEC
# $ kubectl apply -f k8s/secret.yaml
# $ kubectl delete deployments.app goserver
# $ kubectl apply -f k8s/deployment.yaml

##################################
####        Probes            #### 
#################################

#### LivenessProbe --> conteiner saudavel ####
# ....
# spec
#   containers:
# ...
#     livenessProbe:
#       httpGet:
#         path: /healthcheck
#         port: 5000 -> porta do container
#       periodSeconds: 5    -> teste de X em X segundos
#       failureThreshold: 1 -> tentivas necessarias pra o k8s reiniciar o pod
#       timeoutSeconds: 1
#       successThreshold: 1
#       initialDelaySeconds: 10 -> tempo de espera pra começar a verificação
# ....
#       (Caso a requisição tenha problemas o container é reiniciado)
# EXEC
# $ kubectl delete deployments.app goserver
# $ kubectl apply -f k8s/deployment.yaml && kubectl get pods -w

#### ReadinessProbe --> conteiner pronto pra receber conexões ####
# ....
# spec
#   containers:
# ...
#     readinessProbe:
#       httpGet:
#         path: /healthcheck
#         port: 5000 -> porta do container
#       periodSeconds: 5    -> teste de X em X segundos
#       failureThreshold: 1 -> tentivas necessarias pra o k8s reiniciar o pod
#       initialDelaySeconds: 10 -> tempo de espera pra começar a verificação
# ....
#       (Caso a requisição tenha problemas o container não fica disponivel para receber requisições - NON Ready)
# EXEC
# $ kubectl delete deployments.app goserver
# $ kubectl apply -f k8s/deployment.yaml && kubectl get pods -w

#### StartupProbe --> roda apenas 1 vez na inicialização do container ####
# ....
# spec
#   containers:
# ...
#     startupProbe:
#       httpGet:
#         path: /healthcheck
#         port: 5000  -> porta do container
#       periodSeconds: 3    -> teste de X em X segundos
#       failureThreshold: 30 -> tentativas de verificacao do healthcheck
#       initialDelaySeconds: 10 -> tempo de espera pra começar a verificação
# ....
#       (Nesse caso ocorrera a verificacao em até 90 segundos e se estiver ok - readinessProbe e livenessProbe começam a funcionar)
# EXEC
# $ kubectl delete deployments.app goserver
# $ kubectl apply -f k8s/deployment.yaml && kubectl get pods -w
