apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxserver
  labels:
    app: nginxserver
spec:
  selector:
    matchLabels:
      app: nginxserver
  replicas: 2
  template:
    metadata:
      name: "nginxserver"
      labels:
        app: "nginxserver"
    spec:
      containers:
        - name: nginxserver
          image: nginx:latest

# template: define como os pods serão criados.
# Olhe pod.yaml
