apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      name: "goserver"
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "fabiosouzadev/k8s-fullcycle:v6"
          envFrom:
            - configMapRef:
                name: goserver-env
          volumeMounts:
            - mountPath: "/go/myfamily"
              name: config

      volumes:
        - name: config
          configMap:
            name: goserver-family-env
            items:
              - key: members
                path: "family.txt"

# template: define como os pods serão criados.
# Olhe pod.yaml
              
### Variaveis de ambiente ###
### USANDO env #####
# ....
# env:
#   - name: NOME
#     value: "Fabio"
#   - name: IDADE
#     value: "36"
# ...
## Variaveis de ambiente com ConfigMap ##
# ....
# env:
#   - name: NOME
#     valueFrom:
#       configMapKeyRef:
#         name: goserver-env
#         key: NOME
#   - name: IDADE
#     valueFrom:
#       configMapKeyRef:
#         name: goserver-env
#         key: IDADE
# ....
#### USANDO envFrom (pegando todas as variaveis do ConfigMap) ####
# ....
# spec
#   containers:
# ...
#     envFrom:
#       - configMapRef:
#           name: goserver-env
# ....
#### Injetando ConfigMap ####
#....
# spec
#   containers:
# ....
#     volumeMounts:
#       - mountPath: "/go/myfamily"
#         name: config
# ....
#   volumes:
#     - name: config
#       configMap:
#         name: goserver-family-env
#         items:
#           - key: members
#           path: "family.txt"
