apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginxserver
  labels:
    app: nginxserver
spec:
  selector:
    matchLabels:
      app: nginxserver
  replicas: 1
  template:
    metadata:
      name: "nginxserver"
      labels:
        app: "nginxserver"
    spec:
      containers:
        - name: nginxserver
          image: "nginx"

# template: define como os pods serão criados.
# olhe pod.yaml
