# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: goservice-nodeport
  namespace: default
spec:
  selector:
    app: goservice
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001

